version: "3.9"

services:
  proxy:
    container_name: proxy
    image: nginx:alpine
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
    networks:
      - backend

  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - .env.development.local
    tty: true
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - backend
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    container_name: auth_micro_service_db
    ports:
      - "5433:5432"
    env_file:
      - .env.development.local
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  data:
    driver: local
